### ISSUE TITLE
User Story: MVP - Get Show Updates

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#1]
Title: MVP - Get Show Updates

- As a backend API server, I want to query TVMaze's API server, so that I can ETL item updates to my database.

Feature Tasks
- Register with TVMaze for API credentials.
- Add update command to backend API server.
- Add route endpoint GET '/updates' to trigger update ETL.

Acceptance Tests
- Given TVMaze API credentials and the updates URI, when backend API server performs GET queries TVMaze, then backend API server should receive tv show updates for database items.

**Comment by KasonBraley** [comment]
Not implemented for MVP. Shows are retrieved via `/search/shows/:query`
