### ISSUE TITLE
User Story: MVP - POST logout/

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#2]
Title: MVP - POST logout/

- As a backend API server, I want to host a logout endpoint, so that clients can log out of the system.

Feature Tasks
- Add route endpoint POST 'logout/' that accepts a body with credentials.

Acceptance Tests
- Given a POST request to backend API server at route 'logout/', when the request body has the proper credentials, then the account is logged out of the system and an HTTP 200 status code is returned.

**Comment by KasonBraley** [comment]
Simple logout feature based off of email address added.
