### ISSUE TITLE
User Story: MVP - POST login/

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#3]
Title: MVP - POST login/

- As a backend API server, I want to host a login endpoint, so that clients can login on the system.

Feature Tasks
- Add route endpoint POST 'login/' that accepts a body with credentials.

Acceptance Tests
- Given a POST request to backend API server at route 'login/', when the request body has the proper credentials, then the account is logged in on the system and an HTTP 200 status code is returned.

**Comment by KasonBraley** [comment]
Simple login feature based off of email address added.
