### ISSUE TITLE
User Story: MVP - DELETE shows/:userId

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#4]
Title: MVP - DELETE shows/:userId

- As a backend API server, I want to host a login endpoint, so that clients can delete their shows on the system.

Feature Tasks
- Add route endpoint DELETE 'shows/:userId' that accepts a body with credentials and a query string parameter describing the resource to delete.

Acceptance Tests
- Given a DELETE request to backend API server at route 'shows/:userId', when the request body has the proper credentials and a query string parameter describing the resource to delete, and the resource and credentials are both valid, then the resource is logically deleted from the system and an HTTP 204 status code is returned.

**Comment by KasonBraley** [comment]
Using `PUT` to handle the job of `DELETE`. A delete resources is not needed.
