### ISSUE TITLE
User Story: MVP - POST shows/:userId

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#5]
Title: MVP - POST shows/:userId

- As a backend API server, I want to host a shows endpoint, so that clients can add new shows on the system.

Feature Tasks
- Add route endpoint POST 'shows/:userId' that accepts a body with credentials and a query string parameter describing the resource to add.

Acceptance Tests
- Given a POST request to backend API server at route 'shows/:userId', when the request body has the proper credentials and a query string parameter describing the resource to add, and the resource and credentials are both valid, then the resource is added to the system and an HTTP 201 status code is returned.

**Comment by KasonBraley** [comment]
Using PUT to handle the job of POST A post resources is not needed.
