### ISSUE TITLE
User Story: MVP - GET shows/:userId

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#6]
Title: MVP - GET shows/:userId

- As a backend API server, I want to host a shows endpoint, so that clients can query their shows on the system.

Feature Tasks
- Add route endpoint GET 'shows/:userId' that accepts a body with credentials and a query string parameter describing the resource to get.

Acceptance Tests
- Given a GET request to backend API server at route 'show/:userId', when the request body has the proper credentials and a query string parameter describing the resource(s) to get, and the resource and credentials are both valid, then the resource is returned to the client and an HTTP 200 status code is returned.

**Comment by KasonBraley** [comment]
Added
