### ISSUE TITLE
User Story: MVP - UPDATE shows/:userId

### ISSUE THREAD

**Issue by joeivans** [cf-301-group-2021/entertainment-tracker-backend#7]
Title: MVP - UPDATE items/:userId

- As a backend API server, I want to host an shows endpoint, so that clients can update shows on the system.

Feature Tasks
- Add route endpoint UPDATE 'shows/:userId' that accepts a body with credentials and a query string parameter describing the resource to change.

Acceptance Tests
- Given a UPDATE request to backend API server at route 'shows/:userId', when the request body has the proper credentials and a query string parameter describing the resource to update, and the resource and credentials are both valid, then the resource is updated in the system and an HTTP 204 status code is returned.

**Comment by KasonBraley** [comment]
Not implemented for MVP. Shows are updated via PUT
